if(NOT CMAKE_BUILD_TYPE STREQUAL "Release")
    if(NOT WIN32)
        message(STATUS "Using AddressSanitizer and UndefinedBehaviorSanitizer")
        set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -O0 -g -fsanitize=address,undefined -fno-omit-frame-pointer")
    endif()
endif()

find_program(CLANG_TIDY NAMES clang-tidy)
if(CLANG_TIDY)
    set(CMAKE_CXX_CLANG_TIDY "${CLANG_TIDY}")
endif()
