name: clang-tidy and clang-format

on:
  push:
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  clang-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get install -y clang-tidy clang-format ninja-build

      - name: Run clang-tidy
        run: clang-tidy --quiet -p build --warnings-as-errors=* build $(find src/ -name '*.cpp')

      - name: Configure CMake
        run: |
          cmake \
            -B build \
            -G Ninja

      - name: run clang-format
        run: cmake --build build --target format-check

