name: MSVC build on Windows 

on:
  push:
    branches: 
      - "main"
      - "dev"
      - "^[0-9]*"
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        name: Windows MSVC x64
        os: windows-latest
        buildType: Release
        cc: cl
        cxx: cl
        arch: x64
        generators: Visual Studio 17 2022

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set reusable Strings
        id: strings
        run: echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Configure CMake
        run: |
          cmake \
            -S ${{ github.workspace }} \
            -B ${{ steps.strings.outputs.build-output-dir }} \
            -DCMAKE_CXX_COMPILER=${{ matrix.cxx_compiler }} \
            -DCMAKE_C_COMPILER=${{ matrix.c_compiler }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.buildType }} \
            -G ${{ matrix.generator }}

      - name: Build
        run: |
          cmake \
            --build ${{ steps.strings.outputs.build-output-dir }} \
            --config ${{ matrix.buildType }}

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: ctest --build-config ${{ matrix.buildType }}

